package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// runIndex calls cmdIndex and returns its stdout.
func runIndex(t *testing.T, args ...string) string {
	t.Helper()
	kb, _ := openWorkspaceKB(t)
	var out bytes.Buffer
	if err := cmdIndex(kb, nil, false, args, &out); err != nil {
		t.Fatalf("cmdIndex %v: %v", args, err)
	}
	return out.String()
}

// The phase's real acceptance test: two independent implementations agreeing
// on every byte. The live index.md files were generated by
// ~/WorkLab/decisions_index.ts, so comparing against them compares against it.
func TestCmdIndex_ByteIdenticalToLiveIndexes(t *testing.T) {
	dirs := corpusDirsCLI(t)
	for _, dir := range dirs {
		name := filepath.Base(filepath.Dir(dir))
		want, err := os.ReadFile(filepath.Join(dir, "index.md"))
		if err != nil {
			t.Errorf("%s: no live index.md to compare against: %v", name, err)
			continue
		}
		got := runIndex(t, dir, "--stdout")
		if got != string(want) {
			t.Errorf("%s: kb index output differs from the live index.\n--- got ---\n%s\n--- want ---\n%s",
				name, firstDiff(got, string(want)), name)
		}
	}
}

// firstDiff returns a short description of where two strings first differ.
func firstDiff(got, want string) string {
	g := strings.Split(got, "\n")
	w := strings.Split(want, "\n")
	for i := 0; i < len(g) && i < len(w); i++ {
		if g[i] != w[i] {
			return "line " + itoa(i+1) + ":\n got: " + g[i] + "\nwant: " + w[i]
		}
	}
	if len(g) != len(w) {
		return "line counts differ: got " + itoa(len(g)) + ", want " + itoa(len(w))
	}
	return "(identical)"
}

func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	var b []byte
	for n > 0 {
		b = append([]byte{byte('0' + n%10)}, b...)
		n /= 10
	}
	return string(b)
}

// corpusDirsCLI returns the live decision directories, skipping when absent.
func corpusDirsCLI(t *testing.T) []string {
	t.Helper()
	home, err := os.UserHomeDir()
	if err != nil {
		t.Skipf("no home directory: %v", err)
	}
	candidates := []string{
		filepath.Join(home, "WorkLab", "clasm", "decisions"),
		filepath.Join(home, "WorkLab", "CMTools", "decisions"),
		filepath.Join(home, "WorkLab", "cold", "decisions"),
		filepath.Join(home, "WorkLab", "agents", "decisions"),
		filepath.Join(home, "Laboratory", "knowledge", "decisions"),
	}
	var out []string
	for _, d := range candidates {
		if fi, err := os.Stat(d); err == nil && fi.IsDir() {
			out = append(out, d)
		}
	}
	if len(out) == 0 {
		t.Skip("no decision-record corpora on this machine")
	}
	return out
}

// The title must start at $7 under awk's default field splitting, on every
// row, including the many whose trigger is empty.
func TestCmdIndex_TitleIsAlwaysField7(t *testing.T) {
	for _, dir := range corpusDirsCLI(t) {
		name := filepath.Base(filepath.Dir(dir))
		for _, line := range strings.Split(runIndex(t, dir, "--stdout"), "\n") {
			if !strings.HasPrefix(line, "DR-") {
				continue
			}
			if len(strings.Fields(line)) < 7 {
				t.Errorf("%s: row has fewer than 7 fields: %q", name, line)
			}
		}
	}
}

func TestCmdIndex_FlagAndPlaceholderColumns(t *testing.T) {
	kb, root := openWorkspaceKB(t)
	dir := filepath.Join(root, "clasm", "decisions")
	// A wholly superseded record: status says so and the flag fires too.
	testRecord{ID: "0148", Project: "clasm", Status: "superseded",
		SupersededBy: []string{"0149"}, Date: "2026-07-29", Title: "Wholly superseded"}.write(t, dir)
	// A partially superseded record: still accepted, flag is its only signal.
	testRecord{ID: "0160", Project: "clasm", Status: "accepted",
		SupersededBy: []string{"0159"}, Date: "2026-08-18", Title: "Partially superseded"}.write(t, dir)
	// An untouched record with an empty trigger.
	testRecord{ID: "0154", Project: "clasm", Status: "accepted",
		Date: "2026-08-12", Title: "Untouched"}.write(t, dir)

	var out bytes.Buffer
	if err := cmdIndex(kb, nil, false, []string{dir, "--stdout"}, &out); err != nil {
		t.Fatalf("cmdIndex: %v", err)
	}
	rows := map[string]string{}
	for _, line := range strings.Split(out.String(), "\n") {
		if strings.HasPrefix(line, "DR-") {
			rows[strings.Fields(line)[0]] = line
		}
	}

	if f := strings.Fields(rows["DR-0160"]); f[2] != "accepted" || f[5] != "sup" {
		t.Errorf("DR-0160 = %q; want status accepted with the sup flag", rows["DR-0160"])
	}
	if f := strings.Fields(rows["DR-0148"]); f[2] != "superseded" || f[5] != "sup" {
		t.Errorf("DR-0148 = %q; want superseded AND sup", rows["DR-0148"])
	}
	if f := strings.Fields(rows["DR-0154"]); f[4] != "-" || f[5] != "-" {
		t.Errorf("DR-0154 = %q; want - placeholders for empty trigger and flag", rows["DR-0154"])
	}
}

// Newest first, by date then id, both descending — never by id alone.
func TestCmdIndex_SortsNewestFirst(t *testing.T) {
	kb, root := openWorkspaceKB(t)
	dir := filepath.Join(root, "clasm", "decisions")
	testRecord{ID: "0160", Project: "clasm", Date: "2026-08-18"}.write(t, dir)
	testRecord{ID: "0159", Project: "clasm", Date: "2026-08-19"}.write(t, dir)
	testRecord{ID: "0158", Project: "clasm", Date: "2026-08-19"}.write(t, dir)

	var out bytes.Buffer
	if err := cmdIndex(kb, nil, false, []string{dir, "--stdout"}, &out); err != nil {
		t.Fatalf("cmdIndex: %v", err)
	}
	var ids []string
	for _, line := range strings.Split(out.String(), "\n") {
		if strings.HasPrefix(line, "DR-") {
			ids = append(ids, strings.Fields(line)[0])
		}
	}
	want := []string{"DR-0159", "DR-0158", "DR-0160"}
	if strings.Join(ids, ",") != strings.Join(want, ",") {
		t.Errorf("order = %v, want %v", ids, want)
	}
}

func TestCmdIndex_WritesIndexAndNothingElse(t *testing.T) {
	kb, root := openWorkspaceKB(t)
	dir := filepath.Join(root, "clasm", "decisions")
	testRecord{ID: "0001", Project: "clasm"}.write(t, dir)

	var out bytes.Buffer
	if err := cmdIndex(kb, nil, false, []string{dir}, &out); err != nil {
		t.Fatalf("cmdIndex: %v", err)
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("ReadDir: %v", err)
	}
	var names []string
	for _, e := range entries {
		names = append(names, e.Name())
	}
	if len(names) != 2 {
		t.Errorf("directory holds %v, want only the record and index.md", names)
	}
	// Workspace DR-0006 removed README.md from the format; it must not reappear.
	for _, n := range names {
		if n == "README.md" {
			t.Error("kb index created a README.md, which the format no longer has")
		}
	}
}

func TestCmdIndex_IsIdempotent(t *testing.T) {
	kb, root := openWorkspaceKB(t)
	dir := filepath.Join(root, "clasm", "decisions")
	testRecord{ID: "0001", Project: "clasm"}.write(t, dir)
	testRecord{ID: "0002", Project: "clasm", SupersededBy: []string{"0001"}}.write(t, dir)

	var out bytes.Buffer
	if err := cmdIndex(kb, nil, false, []string{dir}, &out); err != nil {
		t.Fatalf("first: %v", err)
	}
	first, _ := os.ReadFile(filepath.Join(dir, "index.md"))
	out.Reset()
	if err := cmdIndex(kb, nil, false, []string{dir}, &out); err != nil {
		t.Fatalf("second: %v", err)
	}
	second, _ := os.ReadFile(filepath.Join(dir, "index.md"))
	if !bytes.Equal(first, second) {
		t.Error("running twice produced a different file")
	}
}

// The attribution line names no tool, so two implementations can produce the
// same bytes without either asserting something false about itself.
func TestCmdIndex_AttributionNamesNoTool(t *testing.T) {
	kb, root := openWorkspaceKB(t)
	dir := filepath.Join(root, "clasm", "decisions")
	testRecord{ID: "0001", Project: "clasm"}.write(t, dir)

	var out bytes.Buffer
	if err := cmdIndex(kb, nil, false, []string{dir, "--stdout"}, &out); err != nil {
		t.Fatalf("cmdIndex: %v", err)
	}
	got := out.String()
	if !strings.Contains(got, "Generated file. Do not hand-edit.") {
		t.Errorf("output is missing the tool-neutral attribution:\n%s", got)
	}
	for _, tool := range []string{"kb index", "decisions_index"} {
		if strings.Contains(got, tool) {
			t.Errorf("attribution names a tool (%q):\n%s", tool, got)
		}
	}
}

func TestCmdIndex_RequiresAPath(t *testing.T) {
	kb, _ := openWorkspaceKB(t)
	var out bytes.Buffer
	if err := cmdIndex(kb, nil, false, nil, &out); err == nil {
		t.Error("expected an error when PATH is missing")
	}
}

func TestCmdIndex_MalformedRecordIsAnError(t *testing.T) {
	kb, root := openWorkspaceKB(t)
	dir := filepath.Join(root, "clasm", "decisions")
	testRecord{ID: "0001", Project: "clasm"}.write(t, dir)
	writeRaw(t, dir, "0002-broken.md", "no frontmatter\n")

	var out bytes.Buffer
	if err := cmdIndex(kb, nil, false, []string{dir, "--stdout"}, &out); err == nil {
		t.Error("a malformed record must not be silently skipped from the index")
	}
}

// ─── search surfacing ────────────────────────────────────────────────────────

func TestCmdSearch_ReportsRecordsAsRecords(t *testing.T) {
	kb, root := openWorkspaceKB(t)
	dir := filepath.Join(root, "clasm", "decisions")
	testRecord{ID: "0160", Project: "clasm",
		Title: "Associate the IAM instance profile",
		Body:  "\n**Context.** A distinctive phrase: zzyzxmarker.\n"}.write(t, dir)
	runIngest(t, kb, dir)

	results, err := kb.Search("zzyzxmarker")
	if err != nil {
		t.Fatalf("Search: %v", err)
	}
	if len(results) == 0 {
		t.Fatal("no results for a record body")
	}
	found := false
	for _, r := range results {
		if r.SourceType == "record" {
			found = true
			if r.Label != "DR-0160" {
				t.Errorf("Label = %q, want DR-0160", r.Label)
			}
		}
	}
	if !found {
		t.Errorf("results = %+v, want one labelled source_type record", results)
	}
}

func TestCmdSearch_StillReportsOtherSourceTypes(t *testing.T) {
	kb, _ := openWorkspaceKB(t)
	pid, err := kb.AddProject("clasm", "distinctive qqxmarker project")
	if err != nil {
		t.Fatalf("AddProject: %v", err)
	}
	if _, err := kb.AddObservation(pid, "note", "another qqxmarker observation"); err != nil {
		t.Fatalf("AddObservation: %v", err)
	}
	results, err := kb.Search("qqxmarker")
	if err != nil {
		t.Fatalf("Search: %v", err)
	}
	seen := map[string]bool{}
	for _, r := range results {
		seen[r.SourceType] = true
	}
	if !seen["project"] || !seen["observation"] {
		t.Errorf("source types seen = %v, want project and observation still reported", seen)
	}
}

// ─── invariants ported from decisions_index_test.ts ──────────────────────────

// The longest value in each vocabulary must fit its column without being
// truncated, or the index would misreport a record's status or trigger.
func TestCmdIndex_DoesNotTruncateLongestVocabularyValues(t *testing.T) {
	kb, root := openWorkspaceKB(t)
	dir := filepath.Join(root, "clasm", "decisions")
	testRecord{ID: "0001", Project: "clasm", Status: "superseded",
		Kind: "refinement", Trigger: "release-review"}.write(t, dir)

	var out bytes.Buffer
	if err := cmdIndex(kb, nil, false, []string{dir, "--stdout"}, &out); err != nil {
		t.Fatalf("cmdIndex: %v", err)
	}
	f := strings.Fields(strings.Split(out.String(), "```\n")[1])
	for i, want := range map[int]string{2: "superseded", 3: "refinement", 4: "release-review"} {
		if f[i] != want {
			t.Errorf("field %d = %q, want %q — the column truncated it", i, f[i], want)
		}
	}
}

// Records are NNNN-slug.md. The generated index.md is in the same directory on
// every run after the first, and must never be read back in as a record.
func TestCmdIndex_IgnoresNonRecordFiles(t *testing.T) {
	kb, root := openWorkspaceKB(t)
	dir := filepath.Join(root, "clasm", "decisions")
	testRecord{ID: "0001", Project: "clasm"}.write(t, dir)
	writeRaw(t, dir, "README.md", "# Prose, not a record\n")
	writeRaw(t, dir, "notes.md", "Also not a record\n")

	var out bytes.Buffer
	if err := cmdIndex(kb, nil, false, []string{dir}, &out); err != nil {
		t.Fatalf("cmdIndex: %v", err)
	}
	// Second run, with index.md now present alongside them.
	out.Reset()
	if err := cmdIndex(kb, nil, false, []string{dir, "--stdout"}, &out); err != nil {
		t.Fatalf("second cmdIndex: %v", err)
	}
	rows := 0
	for _, line := range strings.Split(out.String(), "\n") {
		if strings.HasPrefix(line, "DR-") {
			rows++
		}
	}
	if rows != 1 {
		t.Errorf("index has %d rows, want 1 — a non-record file was read as a record", rows)
	}
}

// relates_to is not an index column, so a qualified cross-tier reference must
// pass through without disturbing anything.
func TestCmdIndex_QualifiedRelatesToDoesNotDisturbTheIndex(t *testing.T) {
	kb, root := openWorkspaceKB(t)
	dir := filepath.Join(root, "agents", "decisions")
	testRecord{ID: "0001", Project: "", RelatesTo: []string{"clasm:0160"}}.write(t, dir)

	var out bytes.Buffer
	if err := cmdIndex(kb, nil, false, []string{dir, "--stdout"}, &out); err != nil {
		t.Fatalf("cmdIndex: %v", err)
	}
	if strings.Contains(out.String(), "clasm:0160") {
		t.Errorf("a relates_to entry leaked into the index:\n%s", out.String())
	}
	if f := strings.Fields(strings.Split(out.String(), "```\n")[1]); len(f) < 7 || f[0] != "DR-0001" {
		t.Errorf("row = %q, want a well-formed DR-0001 row", out.String())
	}
}

func TestCmdIndex_AbsentSupersededByIsEmptyNotFlagged(t *testing.T) {
	kb, root := openWorkspaceKB(t)
	dir := filepath.Join(root, "clasm", "decisions")
	// Written without a superseded_by line at all.
	writeRaw(t, dir, "0001-no-superseded-by.md", `---
id: "0001"
title: "No superseded_by key"
date: "2026-08-25"
status: accepted
kind: decision
trigger: design
project: clasm
phase: ""
supersedes: []
relates_to: []
initiative: ""
session: ""
decisions: []
tags: []
uuid: "44444444-4444-7444-8444-444444444444"
origin_host: "test"
---

**Context.** Absent key.
`)
	var out bytes.Buffer
	if err := cmdIndex(kb, nil, false, []string{dir, "--stdout"}, &out); err != nil {
		t.Fatalf("cmdIndex: %v", err)
	}
	if f := strings.Fields(strings.Split(out.String(), "```\n")[1]); f[5] != "-" {
		t.Errorf("flag column = %q, want the placeholder when superseded_by is absent", f[5])
	}
}
